#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/aefd63a960222650779340cf9b29ee52e7b24ec73b59d10cb37f494167eb1a66/contract';
import endContract from '../../snapshots/aefd63a960222650779340cf9b29ee52e7b24ec73b59d10cb37f494167eb1a66/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'account',
        columns: [
          col('accessToken', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('idToken', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('provider', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('providerAccountId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('refreshToken', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('scope', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tokenType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'artifactEncryption',
        columns: [
          col('algorithm', 'text', {
            notNull: true,
            default: lit('AES-256-GCM'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('dekId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('versionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('wrapNonce', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('wrapTag', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('wrappedDek', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'artifactSignature',
        columns: [
          col('algorithm', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('artifactHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('keyId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('manifest', 'json', { notNull: true, codecRef: { codecId: 'pg/json@1' } }),
          col('manifestHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('signature', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('signedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('verifiedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('versionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'auditLog',
        columns: [
          col('action', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('actorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('after', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('before', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ip', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('requestId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('targetId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('targetType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'compatibilityReport',
        columns: [
          col('architecture', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('mtaVersion', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('os', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('verifiedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('verifiedBy', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('versionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'compatibilityReport_status_check_beb3bfd4',
            "\"status\" IN ('VERIFIED', 'PARTIALLY_VERIFIED', 'UNKNOWN', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'discountCampaign',
        columns: [
          col('code', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('RUB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('endsAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('exclusive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('minOrderAmount', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('perUserLimit', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('scope', 'text', {
            notNull: true,
            default: lit('ALL'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('scopeId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sellerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('startsAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('usageLimit', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('usedCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('value', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'discountCampaign_scope_check_4db24e9b',
            "\"scope\" IN ('ALL', 'RESOURCE', 'SERVICE')",
          ),
          checkExpression(
            'discountCampaign_type_check_ac23c085',
            "\"type\" IN ('PERCENT', 'FIXED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'discountUsage',
        columns: [
          col('amount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('campaignId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('orderId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('orderItemId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'dispute',
        columns: [
          col('closedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('openedById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('purchaseId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reason', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('resolution', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('resolvedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('servicePurchaseId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('OPEN'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('targetType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'dispute_status_check_fccc877f',
            "\"status\" IN ('OPEN', 'WAITING_BUYER', 'WAITING_SELLER', 'UNDER_REVIEW', 'RESOLVED_BUYER', 'RESOLVED_SELLER', 'PARTIAL_REFUND', 'CLOSED')",
          ),
          checkExpression(
            'dispute_targetType_check_04961de8',
            "\"targetType\" IN ('PURCHASE', 'SERVICE_PURCHASE')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'disputeAttachment',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('disputeId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('fileName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('fileRef', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('mimeType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sizeBytes', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('uploadedById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'disputeEvent',
        columns: [
          col('actorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('disputeId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('event', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('fromStatus', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('toStatus', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'disputeMessage',
        columns: [
          col('body', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('disputeId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('senderId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('senderRole', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'financialTransaction',
        columns: [
          col('amount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('balanceAfter', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('relatedPayoutId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('relatedPurchaseId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'financialTransaction_type_check_99e45e10',
            "\"type\" IN ('PAYMENT_RECEIVED', 'PLATFORM_FEE', 'SELLER_REVENUE', 'SELLER_PAYOUT', 'REFUND_TO_BUYER', 'REFUND_FROM_SELLER', 'ADJUSTMENT')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'installation',
        columns: [
          col('challenge', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('installedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('lastHeartbeat', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('licenseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('moduleVersion', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('mtaVersion', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('publicKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('revocationReason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('revokedBy', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('serverName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('serverSerial', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING_VERIFICATION'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('verifiedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'installation_status_check_843ed878',
            "\"status\" IN ('PENDING_VERIFICATION', 'ACTIVE', 'REVOKED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'lease',
        columns: [
          col('artifactHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('capabilities', 'json', { notNull: true, codecRef: { codecId: 'pg/json@1' } }),
          col('expiresAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('installationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('issuedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('lastVerifiedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('licenseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('nonce', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('protocolVersion', 'int4', {
            notNull: true,
            default: lit(2),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('resourceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('resourceVersionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('serverKeyId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('signature', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'ledgerAccount',
        columns: [
          col('code', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('RUB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('kind', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'ledgerAccount_kind_check_d48c17eb',
            "\"kind\" IN ('PLATFORM_CASH', 'SELLER_PENDING', 'SELLER_AVAILABLE', 'PLATFORM_REVENUE', 'PROVIDER_FEES', 'REFUND_RESERVE', 'ADJUSTMENTS')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'ledgerEntry',
        columns: [
          col('accountId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('amount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('RUB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('direction', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('memo', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('orderId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('paymentId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('transactionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'ledgerEntry_direction_check_e2bfd96c',
            "\"direction\" IN ('DEBIT', 'CREDIT')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'license',
        columns: [
          col('activatedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('purchaseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('serverSerial', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('versionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'license_status_check_15f2bee4',
            "\"status\" IN ('ACTIVE', 'REVOKED', 'EXPIRED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'moderationEvent',
        columns: [
          col('actorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('fromStatus', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('resourceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('toStatus', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'order',
        columns: [
          col('buyerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('cancelledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('RUB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('discountTotal', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('finalTotal', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('subtotal', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'order_status_check_aa2991a9',
            "\"status\" IN ('PENDING', 'COMPLETED', 'CANCELLED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'orderItem',
        columns: [
          col('basePrice', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('RUB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('discountAmount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('discountCampaignId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('discountCode', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('finalPrice', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('itemType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('orderId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('platformFee', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('resourceId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sellerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sellerNet', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('serviceId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('titleSnapshot', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'orderItem_itemType_check_1b88d338',
            "\"itemType\" IN ('RESOURCE', 'SERVICE')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'payment',
        columns: [
          col('amount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('RUB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('failedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('orderItemId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('provider', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('providerPaymentId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('purchaseId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('succeededAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'payment_provider_check_7f539d22',
            "\"provider\" IN ('YUKASSA', 'STRIPE', 'TEST')",
          ),
          checkExpression(
            'payment_status_check_c2fd0c5a',
            "\"status\" IN ('PENDING', 'SUCCEEDED', 'SETTLEMENT_PENDING', 'SETTLED', 'FAILED', 'CANCELED', 'REFUNDED', 'PARTIALLY_REFUNDED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'paymentProviderEvent',
        columns: [
          col('attempts', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('eventType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastError', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('objectId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('objectType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('payload', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('payloadHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('processedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('provider', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('providerEventId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('receivedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('RECEIVED'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'paymentProviderEvent_provider_check_7f539d22',
            "\"provider\" IN ('YUKASSA', 'STRIPE', 'TEST')",
          ),
          checkExpression(
            'paymentProviderEvent_status_check_9eba03e5',
            "\"status\" IN ('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'publisherKey',
        columns: [
          col('algorithm', 'text', {
            notNull: true,
            default: lit('EdDSA'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('keyType', 'text', {
            notNull: true,
            default: lit('ED25519'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('publicKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('revocationReason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('revokedBy', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sellerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'publisherKey_status_check_89af429c',
            "\"status\" IN ('ACTIVE', 'PREVIOUS', 'REVOKED', 'EXPIRED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'purchase',
        columns: [
          col('buyerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('discountSnapshot', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('finalPrice', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('orderItemId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('platformFee', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('priceSnapshot', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('refundedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('resourceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sellerRevenue', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('versionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'purchase_status_check_29627081',
            "\"status\" IN ('PENDING', 'COMPLETED', 'REFUNDED', 'DISPUTED', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'reconciliationMismatch',
        columns: [
          col('actualAmount', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('expectedAmount', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('internalId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('providerId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reportId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('resolution', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('resolved', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('resolvedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('resolvedBy', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'reconciliationMismatch_type_check_de98bc65',
            "\"type\" IN ('MISSING_INTERNAL', 'MISSING_PROVIDER', 'AMOUNT_MISMATCH', 'STATUS_MISMATCH')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'reconciliationReport',
        columns: [
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('errorMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('internalCount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('internalTotal', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('mismatchCount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('periodEnd', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('periodStart', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('provider', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('providerCount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('providerTotal', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reportType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'reconciliationReport_reportType_check_29661730',
            "\"reportType\" IN ('PAYMENT', 'REFUND', 'PAYOUT')",
          ),
          checkExpression(
            'reconciliationReport_status_check_5fd92494',
            "\"status\" IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'refund',
        columns: [
          col('amount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('RUB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastError', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('paymentId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('processedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('providerRefundId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'refund_status_check_6abad72d',
            "\"status\" IN ('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'resource',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('price', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('sellerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('DRAFT'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'resource_status_check_acf4673f',
            "\"status\" IN ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'SUSPENDED')",
          ),
          checkExpression(
            'resource_type_check_76c69b54',
            "\"type\" IN ('SCRIPT', 'MAP', 'MODEL', 'TEXTURE', 'SOUND', 'GAMEMODE')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'resourceDependency',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('dependsOnSlug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('minVersion', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('resourceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'resourceVersion',
        columns: [
          col('changelog', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('fileChecksum', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('fileSize', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('fileUrl', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('publishedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('releaseStatus', 'text', {
            notNull: true,
            default: lit('CANDIDATE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('resourceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('version', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'resourceVersion_releaseStatus_check_d9630f26',
            "\"releaseStatus\" IN ('CANDIDATE', 'VERIFIED', 'PUBLISHED', 'DEPRECATED', 'YANKED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'review',
        columns: [
          col('buyerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('comment', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('rating', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('resourceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'sandboxRun',
        columns: [
          col('compatibilityReport', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('containerId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('cpuLimit', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('exitCode', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('memoryLimitMb', 'int4', {
            notNull: true,
            default: lit(512),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('securityReport', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('startedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('staticValidation', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('stderr', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('stdout', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('timeoutSeconds', 'int4', {
            notNull: true,
            default: lit(60),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('versionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'sandboxRun_status_check_bbe909b8',
            "\"status\" IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'SECURITY_VIOLATION')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'sellerBalance',
        columns: [
          col('availableAmount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('inEscrowAmount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('totalEarned', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['userId'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'sellerProfile',
        columns: [
          col('appliedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('displayName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('payoutEnabled', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('rejectionReason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reviewedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('reviewedBy', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('supportInfo', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'sellerProfile_status_check_56005a61',
            "\"status\" IN ('PENDING', 'APPROVED', 'REJECTED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'serverSigningKey',
        columns: [
          col('algorithm', 'text', {
            notNull: true,
            default: lit('EdDSA'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('keyType', 'text', {
            notNull: true,
            default: lit('ED25519'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('publicKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('revocationReason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('revokedBy', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'serverSigningKey_status_check_89af429c',
            "\"status\" IN ('ACTIVE', 'PREVIOUS', 'REVOKED', 'EXPIRED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'service',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deliveryDays', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('price', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('requirements', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sellerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('DRAFT'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'service_status_check_acf4673f',
            "\"status\" IN ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'SUSPENDED')",
          ),
          checkExpression(
            'service_type_check_c82eb75e',
            "\"type\" IN ('CUSTOM_DEVELOPMENT', 'CONFIGURATION', 'SUPPORT', 'CONSULTATION', 'OTHER')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'serviceDelivery',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deliverableRef', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sellerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('servicePurchaseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'serviceOrderItem',
        columns: [
          col('buyerNotes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('discountId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('discountSnapshot', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('finalPrice', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('orderId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('orderItemId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('priceSnapshot', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('quantity', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('serviceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'serviceOrderMessage',
        columns: [
          col('body', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('senderId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('senderRole', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('servicePurchaseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'servicePurchase',
        columns: [
          col('buyerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('cancelledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deliveryDeadline', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('discountSnapshot', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('finalPrice', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('platformFee', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('priceSnapshot', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('sellerRevenue', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('serviceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('serviceOrderItemId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'servicePurchase_status_check_c14a7045',
            "\"status\" IN ('PENDING', 'IN_PROGRESS', 'DELIVERED', 'ACCEPTED', 'CLOSED', 'CANCELLED', 'DISPUTED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'serviceRevision',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deliveryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reason', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('requestedBy', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('resolvedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('servicePurchaseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('OPEN'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'session',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiresAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastRotatedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('refreshTokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reuseDetected', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('tokenFamily', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'user',
        columns: [
          col('avatar', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('displayName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('emailVerified', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('passwordHash', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', {
            notNull: true,
            default: lit('USER'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('username', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('user_role_check_e7d7eb9e', "\"role\" IN ('USER', 'ADMIN', 'MODERATOR')"),
          checkExpression(
            'user_status_check_18a7fd43',
            "\"status\" IN ('ACTIVE', 'SUSPENDED', 'BANNED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'userBalance',
        columns: [
          col('available', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('RUB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['userId'])],
      }),
      this.addUnique({
        schema: 'public',
        table: 'account',
        constraint: 'account_provider_providerAccountId_key',
        columns: ['provider', 'providerAccountId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'artifactEncryption',
        constraint: 'artifactEncryption_versionId_key',
        columns: ['versionId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'artifactEncryption',
        constraint: 'artifactEncryption_dekId_key',
        columns: ['dekId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'artifactSignature',
        constraint: 'artifactSignature_versionId_key',
        columns: ['versionId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'discountCampaign',
        constraint: 'discountCampaign_sellerId_code_key',
        columns: ['sellerId', 'code'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'discountUsage',
        constraint: 'discountUsage_campaignId_orderItemId_key',
        columns: ['campaignId', 'orderItemId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'installation',
        constraint: 'installation_publicKey_key',
        columns: ['publicKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'lease',
        constraint: 'lease_nonce_key',
        columns: ['nonce'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'ledgerAccount',
        constraint: 'ledgerAccount_code_key',
        columns: ['code'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'license',
        constraint: 'license_purchaseId_key',
        columns: ['purchaseId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'payment',
        constraint: 'payment_purchaseId_key',
        columns: ['purchaseId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'payment',
        constraint: 'payment_orderItemId_key',
        columns: ['orderItemId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'payment',
        constraint: 'payment_providerPaymentId_key',
        columns: ['providerPaymentId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'paymentProviderEvent',
        constraint: 'paymentProviderEvent_provider_providerEventId_eventType_key',
        columns: ['provider', 'providerEventId', 'eventType'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'purchase',
        constraint: 'purchase_orderItemId_key',
        columns: ['orderItemId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'refund',
        constraint: 'refund_providerRefundId_key',
        columns: ['providerRefundId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'resource',
        constraint: 'resource_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'resourceDependency',
        constraint: 'resourceDependency_resourceId_dependsOnSlug_key',
        columns: ['resourceId', 'dependsOnSlug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'resourceVersion',
        constraint: 'resourceVersion_resourceId_version_key',
        columns: ['resourceId', 'version'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'review',
        constraint: 'review_resourceId_buyerId_key',
        columns: ['resourceId', 'buyerId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'sellerProfile',
        constraint: 'sellerProfile_userId_key',
        columns: ['userId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'service',
        constraint: 'service_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'serviceOrderItem',
        constraint: 'serviceOrderItem_orderItemId_key',
        columns: ['orderItemId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'servicePurchase',
        constraint: 'servicePurchase_serviceOrderItemId_key',
        columns: ['serviceOrderItemId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'session',
        constraint: 'session_refreshTokenHash_key',
        columns: ['refreshTokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'user',
        constraint: 'user_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'user',
        constraint: 'user_username_key',
        columns: ['username'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'account',
        index: 'account_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'artifactEncryption',
        index: 'artifactEncryption_dekId_idx_ae8dda1d',
        columns: ['dekId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'artifactSignature',
        index: 'artifactSignature_artifactHash_idx_719fc5d6',
        columns: ['artifactHash'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'artifactSignature',
        index: 'artifactSignature_keyId_idx_c75a7d57',
        columns: ['keyId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'artifactSignature',
        index: 'artifactSignature_versionId_idx_ef8aa804',
        columns: ['versionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_actorId_idx_a58f6b4b',
        columns: ['actorId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_targetType_targetId_idx_7a5ee9cb',
        columns: ['targetType', 'targetId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'compatibilityReport',
        index: 'compatibilityReport_versionId_idx_ef8aa804',
        columns: ['versionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'discountCampaign',
        index: 'discountCampaign_isActive_idx_77fe3ba1',
        columns: ['isActive'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'discountCampaign',
        index: 'discountCampaign_sellerId_idx_d71255f2',
        columns: ['sellerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'discountUsage',
        index: 'discountUsage_campaignId_idx_3aacd648',
        columns: ['campaignId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'discountUsage',
        index: 'discountUsage_campaignId_userId_idx_fee48996',
        columns: ['campaignId', 'userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'discountUsage',
        index: 'discountUsage_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'dispute',
        index: 'dispute_purchaseId_idx_10cddd2f',
        columns: ['purchaseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'dispute',
        index: 'dispute_servicePurchaseId_idx_d3ffae5a',
        columns: ['servicePurchaseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'dispute',
        index: 'dispute_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'disputeAttachment',
        index: 'disputeAttachment_disputeId_idx_372fe71f',
        columns: ['disputeId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'disputeEvent',
        index: 'disputeEvent_disputeId_idx_372fe71f',
        columns: ['disputeId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'disputeMessage',
        index: 'disputeMessage_disputeId_idx_372fe71f',
        columns: ['disputeId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'financialTransaction',
        index: 'financialTransaction_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'financialTransaction',
        index: 'financialTransaction_type_idx_b6b604ea',
        columns: ['type'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'financialTransaction',
        index: 'financialTransaction_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'installation',
        index: 'installation_licenseId_idx_bd8730e9',
        columns: ['licenseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'installation',
        index: 'installation_publicKey_idx_ab007bc5',
        columns: ['publicKey'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'installation',
        index: 'installation_serverSerial_idx_032d2105',
        columns: ['serverSerial'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'installation',
        index: 'installation_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lease',
        index: 'lease_expiresAt_idx_6b6b8c10',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lease',
        index: 'lease_installationId_idx_17db6dbe',
        columns: ['installationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lease',
        index: 'lease_issuedAt_idx_a299a849',
        columns: ['issuedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lease',
        index: 'lease_licenseId_idx_bd8730e9',
        columns: ['licenseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lease',
        index: 'lease_nonce_idx_45b28236',
        columns: ['nonce'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lease',
        index: 'lease_serverKeyId_idx_415c1171',
        columns: ['serverKeyId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ledgerAccount',
        index: 'ledgerAccount_kind_idx_c9ca668f',
        columns: ['kind'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ledgerEntry',
        index: 'ledgerEntry_accountId_idx_cbfb3085',
        columns: ['accountId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ledgerEntry',
        index: 'ledgerEntry_transactionId_idx_d3180832',
        columns: ['transactionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ledgerEntry',
        index: 'ledgerEntry_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'license',
        index: 'license_serverSerial_idx_032d2105',
        columns: ['serverSerial'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'license',
        index: 'license_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'license',
        index: 'license_versionId_idx_ef8aa804',
        columns: ['versionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'moderationEvent',
        index: 'moderationEvent_resourceId_idx_72964925',
        columns: ['resourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'order',
        index: 'order_buyerId_idx_80be0de9',
        columns: ['buyerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'order',
        index: 'order_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'orderItem',
        index: 'orderItem_discountCampaignId_idx_e4e0d149',
        columns: ['discountCampaignId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'orderItem',
        index: 'orderItem_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'orderItem',
        index: 'orderItem_sellerId_idx_d71255f2',
        columns: ['sellerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'payment',
        index: 'payment_providerPaymentId_idx_c1a2370c',
        columns: ['providerPaymentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'payment',
        index: 'payment_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'paymentProviderEvent',
        index: 'paymentProviderEvent_objectId_idx_08ca88de',
        columns: ['objectId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'paymentProviderEvent',
        index: 'paymentProviderEvent_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'publisherKey',
        index: 'publisherKey_publicKey_idx_ab007bc5',
        columns: ['publicKey'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'publisherKey',
        index: 'publisherKey_sellerId_idx_d71255f2',
        columns: ['sellerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'publisherKey',
        index: 'publisherKey_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchase',
        index: 'purchase_buyerId_idx_80be0de9',
        columns: ['buyerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchase',
        index: 'purchase_orderItemId_idx_99e2d9f7',
        columns: ['orderItemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchase',
        index: 'purchase_resourceId_idx_72964925',
        columns: ['resourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchase',
        index: 'purchase_versionId_idx_ef8aa804',
        columns: ['versionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reconciliationMismatch',
        index: 'reconciliationMismatch_reportId_idx_d163019e',
        columns: ['reportId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reconciliationMismatch',
        index: 'reconciliationMismatch_resolved_idx_ffe6249d',
        columns: ['resolved'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reconciliationMismatch',
        index: 'reconciliationMismatch_type_idx_b6b604ea',
        columns: ['type'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reconciliationReport',
        index: 'reconciliationReport_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reconciliationReport',
        index: 'reconciliationReport_provider_idx_faf3af28',
        columns: ['provider'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reconciliationReport',
        index: 'reconciliationReport_reportType_idx_4bf915d6',
        columns: ['reportType'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reconciliationReport',
        index: 'reconciliationReport_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'refund',
        index: 'refund_paymentId_idx_b2fe9a10',
        columns: ['paymentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'refund',
        index: 'refund_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'resource',
        index: 'resource_sellerId_idx_d71255f2',
        columns: ['sellerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'resource',
        index: 'resource_slug_idx_73b7f5ce',
        columns: ['slug'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'resource',
        index: 'resource_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'resourceDependency',
        index: 'resourceDependency_resourceId_idx_72964925',
        columns: ['resourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'resourceVersion',
        index: 'resourceVersion_resourceId_idx_72964925',
        columns: ['resourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review',
        index: 'review_buyerId_idx_80be0de9',
        columns: ['buyerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review',
        index: 'review_resourceId_idx_72964925',
        columns: ['resourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sandboxRun',
        index: 'sandboxRun_startedAt_idx_cac56236',
        columns: ['startedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sandboxRun',
        index: 'sandboxRun_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sandboxRun',
        index: 'sandboxRun_versionId_idx_ef8aa804',
        columns: ['versionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serverSigningKey',
        index: 'serverSigningKey_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'service',
        index: 'service_sellerId_idx_d71255f2',
        columns: ['sellerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'service',
        index: 'service_slug_idx_73b7f5ce',
        columns: ['slug'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'service',
        index: 'service_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serviceDelivery',
        index: 'serviceDelivery_servicePurchaseId_idx_d3ffae5a',
        columns: ['servicePurchaseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serviceOrderItem',
        index: 'serviceOrderItem_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serviceOrderItem',
        index: 'serviceOrderItem_serviceId_idx_b5d9acbf',
        columns: ['serviceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serviceOrderMessage',
        index: 'serviceOrderMessage_servicePurchaseId_idx_d3ffae5a',
        columns: ['servicePurchaseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'servicePurchase',
        index: 'servicePurchase_buyerId_idx_80be0de9',
        columns: ['buyerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'servicePurchase',
        index: 'servicePurchase_serviceId_idx_b5d9acbf',
        columns: ['serviceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'servicePurchase',
        index: 'servicePurchase_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serviceRevision',
        index: 'serviceRevision_deliveryId_idx_ebc950f6',
        columns: ['deliveryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serviceRevision',
        index: 'serviceRevision_servicePurchaseId_idx_d3ffae5a',
        columns: ['servicePurchaseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'session',
        index: 'session_expiresAt_idx_6b6b8c10',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'session',
        index: 'session_refreshTokenHash_idx_15b546eb',
        columns: ['refreshTokenHash'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'session',
        index: 'session_tokenFamily_idx_c04c60b5',
        columns: ['tokenFamily'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'session',
        index: 'session_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'user',
        index: 'user_email_idx_46df9cad',
        columns: ['email'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'user',
        index: 'user_username_idx_b719d535',
        columns: ['username'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'account',
        foreignKey: {
          name: 'account_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'artifactEncryption',
        foreignKey: {
          name: 'artifactEncryption_versionId_fkey',
          columns: ['versionId'],
          references: { schema: 'public', table: 'resourceVersion', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'artifactSignature',
        foreignKey: {
          name: 'artifactSignature_versionId_fkey',
          columns: ['versionId'],
          references: { schema: 'public', table: 'resourceVersion', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'artifactSignature',
        foreignKey: {
          name: 'artifactSignature_keyId_fkey',
          columns: ['keyId'],
          references: { schema: 'public', table: 'publisherKey', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'compatibilityReport',
        foreignKey: {
          name: 'compatibilityReport_versionId_fkey',
          columns: ['versionId'],
          references: { schema: 'public', table: 'resourceVersion', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'discountCampaign',
        foreignKey: {
          name: 'discountCampaign_sellerId_fkey',
          columns: ['sellerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'discountUsage',
        foreignKey: {
          name: 'discountUsage_campaignId_fkey',
          columns: ['campaignId'],
          references: { schema: 'public', table: 'discountCampaign', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'dispute',
        foreignKey: {
          name: 'dispute_purchaseId_fkey',
          columns: ['purchaseId'],
          references: { schema: 'public', table: 'purchase', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'dispute',
        foreignKey: {
          name: 'dispute_servicePurchaseId_fkey',
          columns: ['servicePurchaseId'],
          references: { schema: 'public', table: 'servicePurchase', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'disputeAttachment',
        foreignKey: {
          name: 'disputeAttachment_disputeId_fkey',
          columns: ['disputeId'],
          references: { schema: 'public', table: 'dispute', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'disputeEvent',
        foreignKey: {
          name: 'disputeEvent_disputeId_fkey',
          columns: ['disputeId'],
          references: { schema: 'public', table: 'dispute', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'disputeMessage',
        foreignKey: {
          name: 'disputeMessage_disputeId_fkey',
          columns: ['disputeId'],
          references: { schema: 'public', table: 'dispute', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'financialTransaction',
        foreignKey: {
          name: 'financialTransaction_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'installation',
        foreignKey: {
          name: 'installation_licenseId_fkey',
          columns: ['licenseId'],
          references: { schema: 'public', table: 'license', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'lease',
        foreignKey: {
          name: 'lease_installationId_fkey',
          columns: ['installationId'],
          references: { schema: 'public', table: 'installation', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'lease',
        foreignKey: {
          name: 'lease_serverKeyId_fkey',
          columns: ['serverKeyId'],
          references: { schema: 'public', table: 'serverSigningKey', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ledgerEntry',
        foreignKey: {
          name: 'ledgerEntry_accountId_fkey',
          columns: ['accountId'],
          references: { schema: 'public', table: 'ledgerAccount', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'license',
        foreignKey: {
          name: 'license_purchaseId_fkey',
          columns: ['purchaseId'],
          references: { schema: 'public', table: 'purchase', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'license',
        foreignKey: {
          name: 'license_versionId_fkey',
          columns: ['versionId'],
          references: { schema: 'public', table: 'resourceVersion', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'moderationEvent',
        foreignKey: {
          name: 'moderationEvent_resourceId_fkey',
          columns: ['resourceId'],
          references: { schema: 'public', table: 'resource', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'order',
        foreignKey: {
          name: 'order_buyerId_fkey',
          columns: ['buyerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'orderItem',
        foreignKey: {
          name: 'orderItem_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'order', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'orderItem',
        foreignKey: {
          name: 'orderItem_discountCampaignId_fkey',
          columns: ['discountCampaignId'],
          references: { schema: 'public', table: 'discountCampaign', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'publisherKey',
        foreignKey: {
          name: 'publisherKey_sellerId_fkey',
          columns: ['sellerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'purchase',
        foreignKey: {
          name: 'purchase_buyerId_fkey',
          columns: ['buyerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'purchase',
        foreignKey: {
          name: 'purchase_versionId_fkey',
          columns: ['versionId'],
          references: { schema: 'public', table: 'resourceVersion', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'purchase',
        foreignKey: {
          name: 'purchase_orderItemId_fkey',
          columns: ['orderItemId'],
          references: { schema: 'public', table: 'orderItem', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'reconciliationMismatch',
        foreignKey: {
          name: 'reconciliationMismatch_reportId_fkey',
          columns: ['reportId'],
          references: { schema: 'public', table: 'reconciliationReport', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'refund',
        foreignKey: {
          name: 'refund_paymentId_fkey',
          columns: ['paymentId'],
          references: { schema: 'public', table: 'payment', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'resource',
        foreignKey: {
          name: 'resource_sellerId_fkey',
          columns: ['sellerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'resourceDependency',
        foreignKey: {
          name: 'resourceDependency_resourceId_fkey',
          columns: ['resourceId'],
          references: { schema: 'public', table: 'resource', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'resourceVersion',
        foreignKey: {
          name: 'resourceVersion_resourceId_fkey',
          columns: ['resourceId'],
          references: { schema: 'public', table: 'resource', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review',
        foreignKey: {
          name: 'review_resourceId_fkey',
          columns: ['resourceId'],
          references: { schema: 'public', table: 'resource', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review',
        foreignKey: {
          name: 'review_buyerId_fkey',
          columns: ['buyerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sandboxRun',
        foreignKey: {
          name: 'sandboxRun_versionId_fkey',
          columns: ['versionId'],
          references: { schema: 'public', table: 'resourceVersion', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sellerBalance',
        foreignKey: {
          name: 'sellerBalance_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sellerProfile',
        foreignKey: {
          name: 'sellerProfile_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'service',
        foreignKey: {
          name: 'service_sellerId_fkey',
          columns: ['sellerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'serviceDelivery',
        foreignKey: {
          name: 'serviceDelivery_servicePurchaseId_fkey',
          columns: ['servicePurchaseId'],
          references: { schema: 'public', table: 'servicePurchase', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'serviceOrderItem',
        foreignKey: {
          name: 'serviceOrderItem_serviceId_fkey',
          columns: ['serviceId'],
          references: { schema: 'public', table: 'service', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'serviceOrderItem',
        foreignKey: {
          name: 'serviceOrderItem_orderItemId_fkey',
          columns: ['orderItemId'],
          references: { schema: 'public', table: 'orderItem', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'serviceOrderMessage',
        foreignKey: {
          name: 'serviceOrderMessage_servicePurchaseId_fkey',
          columns: ['servicePurchaseId'],
          references: { schema: 'public', table: 'servicePurchase', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'servicePurchase',
        foreignKey: {
          name: 'servicePurchase_serviceOrderItemId_fkey',
          columns: ['serviceOrderItemId'],
          references: { schema: 'public', table: 'serviceOrderItem', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'servicePurchase',
        foreignKey: {
          name: 'servicePurchase_buyerId_fkey',
          columns: ['buyerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'servicePurchase',
        foreignKey: {
          name: 'servicePurchase_serviceId_fkey',
          columns: ['serviceId'],
          references: { schema: 'public', table: 'service', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'serviceRevision',
        foreignKey: {
          name: 'serviceRevision_deliveryId_fkey',
          columns: ['deliveryId'],
          references: { schema: 'public', table: 'serviceDelivery', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'session',
        foreignKey: {
          name: 'session_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'userBalance',
        foreignKey: {
          name: 'userBalance_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
